### PR TITLE
Start of interactive barchart using d3 #114064187

### PR DESCRIPTION
**Pull request by Jessica-L**

### CODE REVIEW

**Comment by Jessica-L** [comment]
@tapa8728: Please review my changes and merge with master/Visualizations

**Comment by Jessica-L** [comment]
@tapa8728: Please review my changes and merge with master/Visualizations

**Comment by tapa8728** [comment]
:+1:  awesome!

**Comment by Jessica-L** [comment]
I'll experiment with this more by or at our meeting tomorrow.  I work at
Seagate 9:15 - 1:15.  See you at the EC at 2 pm! :-)

Regards,

Jessica Lynch
Undergrad (Senior) -- B.S. in Computer Science, Software Engineering at CU
Boulder
Part-time Intern III - Firmware, Integration and Test Process Engineering
at Seagate
303-870-8395
www.linkedin.com/in/jessicalynchcsci/

**Comment by tapa8728** [comment]
@Jessica-L  Excellent!

See you at EC tomorrow! :)
Goodnight!
:last_quarter_moon_with_face:

**Pull request merged**
